using AspNetIdentity.Models;
using AspNetIdentity.WebApi.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;

namespace AspNetIdentity.WebApi.Logic
{
    public class CaracterizacionJuridicaResumenLogic
    {
        BaldiosPersonaNatural ModCtx = new BaldiosPersonaNatural();

        public List<CaracterizacionJuridicaModel>Consultar()
        {
            ZonasFEntities Ctx = new ZonasFEntities();

            var List = Ctx.CaracterizacionJuridica
                .Join(Ctx.Users, b => b.IdAspNetUser, c => c.Id_Hash, (b, c) => new { b, c })
                .Join(Ctx.AspNetUserRoles, b => b.c.Id_Hash, c => c.UserId, (b, c) => new { c.RoleId, b.b, b.c })
                .Join(Ctx.AspNetRoles, b => b.RoleId, c => c.Id, (b, c) => new { b.b, b.c, c.Name })
                .Join(Ctx.BaldiosPersonaNatural, b => b.b.IdExpediente, ll => ll.id, (b, ll) => new { b.b, b.c, ll, b.Name })
                .Select(a => new CaracterizacionJuridicaModel {

                    Id = a.b.Id,
                    IdExpediente = a.b.IdExpediente,
                    NumeroExpediente = a.ll.NumeroExpediente,
                    INSPECCION_OCULAR_INSPECCION_OCULAR_53 = a.b.INSPECCION_OCULAR_INSPECCION_OCULAR_53,
                    INSPECCION_OCULAR_FECHA_54 = a.b.INSPECCION_OCULAR_FECHA_54,
                    INSPECCION_OCULAR_FIRMA_55 = a.b.INSPECCION_OCULAR_FIRMA_55,
                    INSPECCION_OCULAR_OPOSICIONES_56 = a.b.INSPECCION_OCULAR_OPOSICIONES_56,
                    INSPECCION_OCULAR_CONCEPTO_57 = a.b.INSPECCION_OCULAR_CONCEPTO_57,
                    NombreINSPECCION_OCULAR_CONCEPTO_57 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.INSPECCION_OCULAR_CONCEPTO_57.Value).Select(g => g.Nombre).FirstOrDefault(),

                    ACLARACION_DE_INSPECCION_OCULAR_ACLARACION_DE_INSPECCION_OCULAR_58 = a.b.ACLARACION_DE_INSPECCION_OCULAR_ACLARACION_DE_INSPECCION_OCULAR_58,
                    ACLARACION_DE_INSPECCION_OCULAR_FECHA_59 = a.b.ACLARACION_DE_INSPECCION_OCULAR_FECHA_59,
                    ACLARACION_DE_INSPECCION_OCULAR_FIRMA_60 = a.b.ACLARACION_DE_INSPECCION_OCULAR_FIRMA_60,
                    ACLARACION_DE_INSPECCION_OCULAR_CONCEPTO_61 = a.b.ACLARACION_DE_INSPECCION_OCULAR_CONCEPTO_61,
                    NombreACLARACION_DE_INSPECCION_OCULAR_CONCEPTO_61 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.ACLARACION_DE_INSPECCION_OCULAR_CONCEPTO_61.Value).Select(g => g.Nombre).FirstOrDefault(),
                    ACLARACION_DE_INSPECCION_OCULAR_PUBLICACION_EN_EMISORA_62 = a.b.ACLARACION_DE_INSPECCION_OCULAR_PUBLICACION_EN_EMISORA_62,
                    ACLARACION_DE_INSPECCION_OCULAR_FIRMA_DE_PUBLICACION_63 = a.b.ACLARACION_DE_INSPECCION_OCULAR_FIRMA_DE_PUBLICACION_63,

                    FIJACION_EN_LISTA_FIJACION_EN_LISTA_64 = a.b.FIJACION_EN_LISTA_FIJACION_EN_LISTA_64,
                    FIJACION_EN_LISTA_FECHA_DE_FIJACION_65 = a.b.FIJACION_EN_LISTA_FECHA_DE_FIJACION_65,
                    FIJACION_EN_LISTA_FECHA_DE_DESFIJACION_66 = a.b.FIJACION_EN_LISTA_FECHA_DE_DESFIJACION_66,
                    FIJACION_EN_LISTA_FIRMA_67 = a.b.FIJACION_EN_LISTA_FIRMA_67,

                    OPOCISIONES_OPOCISIONES_68 = a.b.OPOCISIONES_OPOCISIONES_68,
                    OPOCISIONES_FECHA_69 = a.b.OPOCISIONES_FECHA_69,

                    FORMATO_DE_REVISION_JURIDICA_FORMATO_DE_REVISION_JURIDICA_70 = a.b.FORMATO_DE_REVISION_JURIDICA_FORMATO_DE_REVISION_JURIDICA_70,
                    FORMATO_DE_REVISION_JURIDICA_FECHA_71 = a.b.FORMATO_DE_REVISION_JURIDICA_FECHA_71,
                    FORMATO_DE_REVISION_JURIDICA_FIRMADA_72 = a.b.FORMATO_DE_REVISION_JURIDICA_FIRMADA_72,
                    FORMATO_DE_REVISION_JURIDICA_CONCEPTO_73 = a.b.FORMATO_DE_REVISION_JURIDICA_CONCEPTO_73,
                    NombreFORMATO_DE_REVISION_JURIDICA_CONCEPTO_73 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.FORMATO_DE_REVISION_JURIDICA_CONCEPTO_73.Value).Select(g => g.Nombre).FirstOrDefault(),

                    RESOLUCION_RESOLUCION_74 = a.b.RESOLUCION_RESOLUCION_74,
                    RESOLUCION_NUMERO_DE_RESOLUCION_75 = a.b.RESOLUCION_NUMERO_DE_RESOLUCION_75,
                    RESOLUCION_FECHA_DE_RESOLUCION_76 = a.b.RESOLUCION_FECHA_DE_RESOLUCION_76,
                    RESOLUCION_FIRMADA_77 = a.b.RESOLUCION_FIRMADA_77,
                    RESOLUCION_DECISION_78 = a.b.RESOLUCION_DECISION_78,
                    NombreRESOLUCION_DECISION_78 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RESOLUCION_DECISION_78.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RESOLUCION_AREA_ADJUDICADA_metros_cuadrados_79 = a.b.RESOLUCION_AREA_ADJUDICADA_metros_cuadrados_79,
                    NombreRESOLUCION_CONJUNTA_INDIVIDUAL_80 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RESOLUCION_CONJUNTA_INDIVIDUAL_80.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RESOLUCION_CONJUNTA_INDIVIDUAL_80 = a.b.RESOLUCION_CONJUNTA_INDIVIDUAL_80,

                    NOTIFICACION_NOTIFICACION_SOLICITANTES_81 = a.b.NOTIFICACION_NOTIFICACION_SOLICITANTES_81,
                    NOTIFICACION_FECHA_DE_NOTIFICACION_SOLICITANTES_82 = a.b.NOTIFICACION_FECHA_DE_NOTIFICACION_SOLICITANTES_82,
                    NOTIFICACION_NOTIFICACION_MINISTERIO_PUBLICO_83 = a.b.NOTIFICACION_NOTIFICACION_MINISTERIO_PUBLICO_83,
                    NOTIFICACION_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_84 = a.b.NOTIFICACION_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_84,

                    RECURSO_SOLICITANTE_DECISION_N_1 = a.b.RECURSO_SOLICITANTE_DECISION_N_1,
                    nombreRECURSO_SOLICITANTE_DECISION_N_1 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_SOLICITANTE_DECISION_N_1.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_SOLICITANTE_RESOLUCION_DESPUES_PRUEBA_N_2 = a.b.RECURSO_SOLICITANTE_RESOLUCION_DESPUES_PRUEBA_N_2,
                    RECURSO_SOLICITANTE_NUMERO_RESOLUCION_DESPUES_PRUEBA_N_3 = a.b.RECURSO_SOLICITANTE_NUMERO_RESOLUCION_DESPUES_PRUEBA_N_3,
                    RECURSO_SOLICITANTE_FECHA_RESOLUCION_PRUEBAS_N_4 = a.b.RECURSO_SOLICITANTE_FECHA_RESOLUCION_PRUEBAS_N_4,
                    RECURSO_SOLICITANTE_FIRMA_RESOLUCION_PRUEBAS_N_5 = a.b.RECURSO_SOLICITANTE_FIRMA_RESOLUCION_PRUEBAS_N_5,
                    RECURSO_SOLICITANTE_DECISION_RESOLUCION_PRUEBAS_N_6 = a.b.RECURSO_SOLICITANTE_DECISION_RESOLUCION_PRUEBAS_N_6,
                    nombreRECURSO_SOLICITANTE_DECISION_RESOLUCION_PRUEBAS_N_6 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_SOLICITANTE_DECISION_RESOLUCION_PRUEBAS_N_6.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_SOLICITANTE_AREA_ADJUDICADA_N_6 = a.b.RECURSO_SOLICITANTE_AREA_ADJUDICADA_N_6,
                    RECURSO_SOLICITANTE_CONJUNA_IND_N_7 = a.b.RECURSO_SOLICITANTE_CONJUNA_IND_N_7,
                    nombreRECURSO_SOLICITANTE_CONJUNA_IND_N_7 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_SOLICITANTE_CONJUNA_IND_N_7.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_SOLICITANTE_NOTIFICACION_SOLICITANTES_N_8 = a.b.RECURSO_SOLICITANTE_NOTIFICACION_SOLICITANTES_N_8,
                    RECURSO_SOLICITANTE_FECHA_DE_NOTIFICACION_SOLICITANTES_N_9 = a.b.RECURSO_SOLICITANTE_FECHA_DE_NOTIFICACION_SOLICITANTES_N_9,
                    RECURSO_SOLICITANTE_NOTIFICACION_MINISTERIO_PUBLICO_N_10 = a.b.RECURSO_SOLICITANTE_NOTIFICACION_MINISTERIO_PUBLICO_N_10,
                    RECURSO_SOLICITANTE_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_N_11 = a.b.RECURSO_SOLICITANTE_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_N_11,
                    RECURSO_SOLICITANTE_RECURSO_SOLICITANTE_85 = a.b.RECURSO_SOLICITANTE_RECURSO_SOLICITANTE_85,
                    RECURSO_SOLICITANTE_FECHA_DE_SOLICITUD_86 = a.b.RECURSO_SOLICITANTE_FECHA_DE_SOLICITUD_86,
                    RECURSO_SOLICITANTE_RESPUESTA_RECURSO_87 = a.b.RECURSO_SOLICITANTE_RESPUESTA_RECURSO_87,
                    RECURSO_SOLICITANTE_FIRMADA_88 = a.b.RECURSO_SOLICITANTE_FIRMADA_88,
                    RECURSO_SOLICITANTE_ACTO_89 = a.b.RECURSO_SOLICITANTE_ACTO_89,
                    nombreRECURSO_SOLICITANTE_ACTO_89 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_SOLICITANTE_ACTO_89.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_SOLICITANTE_NUMERO_90 = a.b.RECURSO_SOLICITANTE_NUMERO_90,
                    RECURSO_SOLICITANTE_FECHA_91 = a.b.RECURSO_SOLICITANTE_FECHA_91,
                    RECURSO_SOLICITANTE_DECISION_SOBRE_LA_ADJUDICAICON_92 = a.b.RECURSO_SOLICITANTE_DECISION_SOBRE_LA_ADJUDICAICON_92,
                    nombreRECURSO_SOLICITANTE_DECISION_SOBRE_LA_ADJUDICAICON_92 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_SOLICITANTE_DECISION_SOBRE_LA_ADJUDICAICON_92.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_SOLICITANTE_NOTIFICACION_SOLICITANTES_93 = a.b.RECURSO_SOLICITANTE_NOTIFICACION_SOLICITANTES_93,
                    RECURSO_SOLICITANTE_FECHA_DE_NOTIFICACION_SOLICITANTES_94 = a.b.RECURSO_SOLICITANTE_FECHA_DE_NOTIFICACION_SOLICITANTES_94,
                    RECURSO_SOLICITANTE_NOTIFICACION_MINISTERIO_PUBLICO_95 = a.b.RECURSO_SOLICITANTE_NOTIFICACION_MINISTERIO_PUBLICO_95,
                    RECURSO_SOLICITANTE_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_96 = a.b.RECURSO_SOLICITANTE_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_96,


                    RECURSO_MINISTERIO_DECISION_N_1 = a.b.RECURSO_MINISTERIO_DECISION_N_1,
                    nombreRECURSO_MINISTERIO_DECISION_N_1 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_MINISTERIO_DECISION_N_1.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_MINISTERIO_RESOLUCION_DESPUES_PRUEBA_N_2 = a.b.RECURSO_MINISTERIO_RESOLUCION_DESPUES_PRUEBA_N_2,
                    RECURSO_MINISTERIO_NUMERO_RESOLUCION_DESPUES_PRUEBA_N_3 = a.b.RECURSO_MINISTERIO_NUMERO_RESOLUCION_DESPUES_PRUEBA_N_3,
                    RECURSO_MINISTERIO_FECHA_RESOLUCION_PRUEBAS_N_4 = a.b.RECURSO_MINISTERIO_FECHA_RESOLUCION_PRUEBAS_N_4,
                    RECURSO_MINISTERIO_FIRMA_RESOLUCION_PRUEBAS_N_5 = a.b.RECURSO_MINISTERIO_FIRMA_RESOLUCION_PRUEBAS_N_5,
                    RECURSO_MINISTERIO_DECISION_RESOLUCION_PRUEBAS_N_6 = a.b.RECURSO_MINISTERIO_DECISION_RESOLUCION_PRUEBAS_N_6,
                    nombreRECURSO_MINISTERIO_DECISION_RESOLUCION_PRUEBAS_N_6 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_MINISTERIO_DECISION_RESOLUCION_PRUEBAS_N_6.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_MINISTERIO_AREA_ADJUDICADA_N_6 = a.b.RECURSO_MINISTERIO_AREA_ADJUDICADA_N_6,
                    RECURSO_MINISTERIO_CONJUNA_IND_N_7 = a.b.RECURSO_MINISTERIO_CONJUNA_IND_N_7,
                    nombreRECURSO_MINISTERIO_CONJUNA_IND_N_7 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_MINISTERIO_CONJUNA_IND_N_7.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_MINISTERIO_NOTIFICACION_SOLICITANTES_N_8 = a.b.RECURSO_MINISTERIO_NOTIFICACION_SOLICITANTES_N_8,
                    RECURSO_MINISTERIO_FECHA_DE_NOTIFICACION_SOLICITANTES_N_9 = a.b.RECURSO_MINISTERIO_FECHA_DE_NOTIFICACION_SOLICITANTES_N_9,
                    RECURSO_MINISTERIO_NOTIFICACION_MINISTERIO_PUBLICO_N_10 = a.b.RECURSO_MINISTERIO_NOTIFICACION_MINISTERIO_PUBLICO_N_10,
                    RECURSO_MINISTERIO_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_N_11 = a.b.RECURSO_MINISTERIO_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_N_11,
                    RECURSO_MINISTERIO_RECURSO_MINISTERIO_85 = a.b.RECURSO_MINISTERIO_RECURSO_MINISTERIO_85,
                    RECURSO_MINISTERIO_FECHA_DE_SOLICITUD_86 = a.b.RECURSO_MINISTERIO_FECHA_DE_SOLICITUD_86,
                    RECURSO_MINISTERIO_RESPUESTA_RECURSO_87 = a.b.RECURSO_MINISTERIO_RESPUESTA_RECURSO_87,
                    RECURSO_MINISTERIO_FIRMADA_88 = a.b.RECURSO_MINISTERIO_FIRMADA_88,
                    RECURSO_MINISTERIO_ACTO_89 = a.b.RECURSO_MINISTERIO_ACTO_89,
                    nombreRECURSO_MINISTERIO_ACTO_89 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_MINISTERIO_ACTO_89.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_MINISTERIO_NUMERO_90 = a.b.RECURSO_MINISTERIO_NUMERO_90,
                    RECURSO_MINISTERIO_FECHA_91 = a.b.RECURSO_MINISTERIO_FECHA_91,
                    RECURSO_MINISTERIO_DECISION_SOBRE_LA_ADJUDICAICON_92 = a.b.RECURSO_MINISTERIO_DECISION_SOBRE_LA_ADJUDICAICON_92,
                    nombreRECURSO_MINISTERIO_DECISION_SOBRE_LA_ADJUDICAICON_92 = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.RECURSO_MINISTERIO_DECISION_SOBRE_LA_ADJUDICAICON_92.Value).Select(g => g.Nombre).FirstOrDefault(),
                    RECURSO_MINISTERIO_NOTIFICACION_SOLICITANTES_93 = a.b.RECURSO_MINISTERIO_NOTIFICACION_SOLICITANTES_93,
                    RECURSO_MINISTERIO_FECHA_DE_NOTIFICACION_SOLICITANTES_94 = a.b.RECURSO_MINISTERIO_FECHA_DE_NOTIFICACION_SOLICITANTES_94,
                    RECURSO_MINISTERIO_NOTIFICACION_MINISTERIO_PUBLICO_95 = a.b.RECURSO_MINISTERIO_NOTIFICACION_MINISTERIO_PUBLICO_95,
                    RECURSO_MINISTERIO_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_96 = a.b.RECURSO_MINISTERIO_FECHA_DE_NOTIFICACION_MINISTERIO_PUBLICO_96,


                    CONSTANCIA_DE_EJECUTORIA_CONSTANCIA_DE_EJECUTOIA_109 = a.b.CONSTANCIA_DE_EJECUTORIA_CONSTANCIA_DE_EJECUTOIA_109,
                    CONSTANCIA_DE_EJECUTORIA_FECHA_CONSTANCIA_EJECUTORIA_110 = a.b.CONSTANCIA_DE_EJECUTORIA_FECHA_CONSTANCIA_EJECUTORIA_110,
                    CONSTANCIA_DE_EJECUTORIA_FIRMADA_111 = a.b.CONSTANCIA_DE_EJECUTORIA_FIRMADA_111,
                    CONSTANCIA_DE_EJECUTORIA_LA_FECHA_ES_CORRECTA_112 = a.b.CONSTANCIA_DE_EJECUTORIA_LA_FECHA_ES_CORRECTA_112,
                    CONSTANCIA_DE_EJECUTORIA_NUMERO_RESOLUCION = a.b.CONSTANCIA_DE_EJECUTORIA_NUMERO_RESOLUCION,
                    CONSTANCIA_DE_EJECUTORIA_NUMERO_RESOLUCION_FECHA = a.b.CONSTANCIA_DE_EJECUTORIA_NUMERO_RESOLUCION_FECHA,

                    REVOCATORIA_REVOCATORIA_113 = a.b.REVOCATORIA_REVOCATORIA_113,
                    REVOCATORIA_NUMERO_RESOLUCION_114 = a.b.REVOCATORIA_NUMERO_RESOLUCIÓN_114,
                    REVOCATORIA_FECHA_DE_RESOLUCION_115 = a.b.REVOCATORIA_FECHA_DE_RESOLUCIÓN_115,
                    REGISTRO_FMI_ = a.b.REGISTRO_FMI_,
                    REGISTRO_FMI = a.b.REGISTRO_FMI,
                    REGISTRO_FECHA_DE_REGISTRO_117 = a.b.REGISTRO_FECHA_DE_REGISTRO_117,
                    REGISTRO_NUMERO_DE_RESOLUCION_118 = a.b.REGISTRO_NUMERO_DE_RESOLUCION_118,
                    REGISTRO_FECHA_DE_RESOLUCION_119 = a.b.REGISTRO_FECHA_DE_RESOLUCION_119,

                    SOLICITUD_SOLICITUD = a.b.SOLICITUD_SOLICITUD,
                    SOLICITUD_FECHA = a.b.SOLICITUD_FECHA,
                    SOLICITUD_FIRMA = a.b.SOLICITUD_FIRMA,
                    SOLICITUD_TIPO_SOLICITUD = a.b.SOLICITUD_TIPO_SOLICITUD,
                    nombreSOLICITUD_TIPO_SOLICITUD = Ctx.CaracterizacionJuridicaCatalogos.Where(x => x.Id == a.b.SOLICITUD_TIPO_SOLICITUD.Value).Select(g => g.Nombre).FirstOrDefault(),
                    SOLICITUD_CEDULA_SOLICITANTE = a.b.SOLICITUD_CEDULA_SOLICITANTE,
                    SOLICITUD_CEDULA_CONYUGE = a.b.SOLICITUD_CEDULA_CONYUGE,
                    SOLICITUD_CEDULA_PARIENTE = a.b.SOLICITUD_CEDULA_PARIENTE,
                    SOLICITUD_FECHADESDELACUALOCUPAEXPLOTA = a.b.SOLICITUD_FECHADESDELACUALOCUPAEXPLOTA,

                    AUTODEACEPTACION_AUTODEACEPTACION = a.b.AUTODEACEPTACION_AUTODEACEPTACION,
                    AUTODEACEPTACION_FECHA = a.b.AUTODEACEPTACION_FECHA,
                    AUTODEACEPTACION_FIRMA = a.b.AUTODEACEPTACION_FIRMA,
                    AUTODEACEPTACION_ELNUMEROFECHADESOLICITUDCORRECTO = a.b.AUTODEACEPTACION_ELNUMEROFECHADESOLICITUDCORRECTO,
                    AUTODEACEPTACION_NOMBRESOLICITANTECONYUGECORRECTO = a.b.AUTODEACEPTACION_NOMBRESOLICITANTECONYUGECORRECTO,
                    AUTODEACEPTACION_DATOSPREDIOSCORRECTO = a.b.AUTODEACEPTACION_DATOSPREDIOSCORRECTO,

                    COMUNICACIONES_SOLICITANTE = a.b.COMUNICACIONES_SOLICITANTE,
                    COMUNICACIONES_SOLICITANTEFECHA = a.b.COMUNICACIONES_SOLICITANTEFECHA,
                    COMUNICACIONES_SOLICITANTEFIRMA = a.b.COMUNICACIONES_SOLICITANTEFIRMA,
                    COMUNICACIONES_FECHAINSPECCIONOCULAR = a.b.COMUNICACIONES_FECHAINSPECCIONOCULAR,
                    COMUNICACIONES_PROCURADOR = a.b.COMUNICACIONES_PROCURADOR,
                    COMUNICACIONES_PROCURADORFECHA = a.b.COMUNICACIONES_PROCURADORFECHA,
                    COMUNICACIONES_PROCURADORFIRMA = a.b.COMUNICACIONES_PROCURADORFIRMA,
                    COMUNICACIONES_AUTORIDADAMBIENTAL = a.b.COMUNICACIONES_AUTORIDADAMBIENTAL,
                    COMUNICACIONES_AUTORIDADAMBIENTALFECHA = a.b.COMUNICACIONES_AUTORIDADAMBIENTALFECHA,
                    COMUNICACIONES_AUTORIDADAMBIENTALFIRMA = a.b.COMUNICACIONES_AUTORIDADAMBIENTALFIRMA,
                    COMUNICACIONES_COLINDATES = a.b.COMUNICACIONES_COLINDATES,
                    COMUNICACIONES_COLINDATESFECHA = a.b.COMUNICACIONES_COLINDATESFECHA,
                    COMUNICACIONES_COLINDATESFIRMA = a.b.COMUNICACIONES_COLINDATESFIRMA,

                    PUBLICACIONES_ALCALDIA = a.b.PUBLICACIONES_ALCALDIA,
                    PUBLICACIONES_ALCALDIAFECHAFIJACION = a.b.PUBLICACIONES_ALCALDIAFECHAFIJACION,
                    PUBLICACIONES_ALCALDIADESFIJACION = a.b.PUBLICACIONES_ALCALDIADESFIJACION,
                    PUBLICACIONES_ALCALDIAFIRMA = a.b.PUBLICACIONES_ALCALDIAFIRMA,
                    PUBLICACIONES_INCODER = a.b.PUBLICACIONES_INCODER,
                    PUBLICACIONES_INCODERFECHAFIJACION = a.b.PUBLICACIONES_INCODERFECHAFIJACION,
                    PUBLICACIONES_INCODERDESFIJACION = a.b.PUBLICACIONES_INCODERDESFIJACION,
                    PUBLICACIONES_INCODERFIRMA = a.b.PUBLICACIONES_INCODERFIRMA,
                    PUBLICACIONES_EMISORA = a.b.PUBLICACIONES_EMISORA,
                    PUBLICACIONES_EMISORAFECHA1 = a.b.PUBLICACIONES_EMISORAFECHA1,
                    PUBLICACIONES_EMISORAFECHA2 = a.b.PUBLICACIONES_EMISORAFECHA2,
                    PUBLICACIONES_EMISORAFIRMA = a.b.PUBLICACIONES_EMISORAFIRMA,

                    INSPECCION_OCULAR_VISIBLE = a.b.INSPECCION_OCULAR_VISIBLE,
                    ACLARACION_DE_INSPECCION_VISIBLE = a.b.ACLARACION_DE_INSPECCION_VISIBLE,
                    FIJACION_EN_LISTA_VISIBLE = a.b.FIJACION_EN_LISTA_VISIBLE,
                    OPOCISIONES_EN_LISTA_VISIBLE = a.b.OPOCISIONES_EN_LISTA_VISIBLE,
                    FORMATO_DE_REVISION_JURIDICA_VISIBLE = a.b.FORMATO_DE_REVISION_JURIDICA_VISIBLE,
                    RESOLUCION_VISIBLE = a.b.RESOLUCION_VISIBLE,
                    NOTIFICACION_VISIBLE = a.b.NOTIFICACION_VISIBLE,
                    RECURSO_SOLICITANTE_VISIBLE = a.b.RECURSO_SOLICITANTE_VISIBLE,
                    RECURSO_MINISTERIO_VISIBLE = a.b.RECURSO_MINISTERIO_VISIBLE,
                    CONSTANCIA_DE_EJECUTORIA_VISIBLE = a.b.CONSTANCIA_DE_EJECUTORIA_VISIBLE,
                    REVOCATORIA_VISIBLE = a.b.REVOCATORIA_VISIBLE,
                    REGISTRO_VISIBLE = a.b.REGISTRO_VISIBLE,
                    SOLICITUD_VISIBLE = a.b.SOLICITUD_VISIBLE,
                    AUTODEACEPTACION_VISIBLE = a.b.AUTODEACEPTACION_VISIBLE,
                    COMUNICACIONES_VISIBLE = a.b.COMUNICACIONES_VISIBLE,
                    PUBLICACIONES_VISIBLE = a.b.PUBLICACIONES_VISIBLE,
                    AUTODEACEPTACION_COLINDANTE_CORRECTO = a.b.AUTODEACEPTACION_COLINDANTE_CORRECTO,
                    COMUNICACIONES_COLINDATES_INCOMPLETOS = a.b.COMUNICACIONES_COLINDATES_INCOMPLETOS,
                    RESOLUCION_DATOS_SOLICITANTE_BIEN = a.b.RESOLUCION_DATOS_SOLICITANTE_BIEN,
                    RESOLUCION_DATOS_SOLICITANTE_EN = a.b.RESOLUCION_DATOS_SOLICITANTE_EN,
                    Estado = true,
                    IdAspNetUser = a.b.IdAspNetUser,
                    rol = a.Name,
                    NombreIdAspNetUser = a.c.Name + " " + a.c.FirstName + " " + a.c.LastName,
                    FechaModificacion = a.b.FechaModificacion,
                    Gestion = a.b.Gestion,
                } ).ToList();

            

            return List;
        }
    }
}