//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int Id_Account { get; set; }
        public int Id_Country { get; set; }
        public string Id_Code { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ImageName { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
        public Nullable<int> LastChangeUser { get; set; }
    }
}
