//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ba_Memorando
    {
        public long Id { get; set; }
        public System.DateTime FechaInsercion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Gestion { get; set; }
        public string IdAspNetUser { get; set; }
        public string IdAspNetUserModifica { get; set; }
        public Nullable<long> IdExpediente { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Validacion1 { get; set; }
        public string Validacion2 { get; set; }
        public string Validacion3 { get; set; }
        public string Validacion4 { get; set; }
        public string Validacion5 { get; set; }
        public string Validacion6 { get; set; }
        public string Validacion7 { get; set; }
        public string Validacion8 { get; set; }
        public string Validacion9 { get; set; }
        public string Validacion10 { get; set; }
        public string Validacion11 { get; set; }
        public string Validacion12 { get; set; }
        public string Validacion13 { get; set; }
        public string Validacion14 { get; set; }
        public string Validacion15 { get; set; }
        public string Validacion16 { get; set; }
        public string Validacion17 { get; set; }
        public string Validacion18 { get; set; }
        public string Validacion19 { get; set; }
        public string Validacion20 { get; set; }
        public string Validacion21 { get; set; }
        public string Validacion22 { get; set; }
        public string Validacion23 { get; set; }
        public string Validacion24 { get; set; }
        public string Validacion25 { get; set; }
        public string Validacion26 { get; set; }
        public string Validacion27 { get; set; }
        public string Validacion28 { get; set; }
        public string Validacion29 { get; set; }
        public string Validacion30 { get; set; }
        public string Validacion31 { get; set; }
        public string Validacion32 { get; set; }
        public string Validacion33 { get; set; }
        public string Validacion34 { get; set; }
        public string Validacion35 { get; set; }
        public string Validacion36 { get; set; }
        public string Validacion37 { get; set; }
        public string Validacion38 { get; set; }
        public string Validacion39 { get; set; }
        public string Validacion40 { get; set; }
        public string Validacion41 { get; set; }
        public string Validacion42 { get; set; }
        public string Validacion43 { get; set; }
        public string Validacion44 { get; set; }
        public string Validacion45 { get; set; }
        public string Validacion46 { get; set; }
        public string Validacion47 { get; set; }
        public string Validacion48 { get; set; }
        public string Validacion49 { get; set; }
        public string Validacion50 { get; set; }
        public string Validacion51 { get; set; }
        public string Validacion52 { get; set; }
        public string Validacion53 { get; set; }
        public string Validacion54 { get; set; }
        public string Validacion55 { get; set; }
        public string Validacion56 { get; set; }
        public string Validacion57 { get; set; }
        public string Validacion58 { get; set; }
        public string Validacion59 { get; set; }
        public string Validacion60 { get; set; }
        public string Validacion61 { get; set; }
        public string Validacion62 { get; set; }
        public string Validacion63 { get; set; }
    }
}
