//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ba_Memorando_new
    {
        public long Id { get; set; }
        public string radicado { get; set; }
        public string cargaorfeo { get; set; }
        public string asignado { get; set; }
        public Nullable<System.DateTime> Fechasignado { get; set; }
        public Nullable<System.DateTime> feacharadicado { get; set; }
        public Nullable<int> fiso { get; set; }
        public string municipio { get; set; }
        public string departamento { get; set; }
        public string expediente { get; set; }
        public Nullable<System.DateTime> fechafiso { get; set; }
        public string tiposolicitud { get; set; }
        public string solicitante { get; set; }
        public string docidentificacionsol { get; set; }
        public string copiadoc { get; set; }
        public string copiacertificadocurso { get; set; }
        public string declararentasol { get; set; }
        public string beneficiariosol { get; set; }
        public string propietariosol { get; set; }
        public string penjudicialessol { get; set; }
        public string ocupanteindebidosol { get; set; }
        public string victimadsol { get; set; }
        public string conyuge { get; set; }
        public string docidentificacioncony { get; set; }
        public string declararentacony { get; set; }
        public string beneficiariocony { get; set; }
        public string propietariocony { get; set; }
        public string penjudicialescony { get; set; }
        public string ocupanteindevidocony { get; set; }
        public string victimadcony { get; set; }
        public string inclusionreso { get; set; }
        public string respojuridico { get; set; }
        public string respoagronomo { get; set; }
        public string respocatastral { get; set; }
        public string responsable { get; set; }
        public string fechaediccion { get; set; }
        public Nullable<System.DateTime> FechaInsercion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Gestion { get; set; }
        public string IdAspNetUser { get; set; }
        public string IdAspNetUserModifica { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
