//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaldiosPersonaNatural
    {
        public long id { get; set; }
        public string NumeroExpediente { get; set; }
        public Nullable<long> IdDepto { get; set; }
        public Nullable<long> IdCiudad { get; set; }
        public string Vereda { get; set; }
        public string NombrePredio { get; set; }
        public string NombreBeneficiario { get; set; }
        public Nullable<int> IdTipoIdentificacion { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public Nullable<long> IdTipoIdentificacionConyuge { get; set; }
        public string IdentificacionConyuge { get; set; }
        public string NombreConyuge { get; set; }
        public string EstadoInicialMigracion { get; set; }
        public string IdAspNetUser { get; set; }
        public Nullable<bool> EstadoCaracterizacion { get; set; }
        public string RutaArchivoOriginal { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<int> ArchivoVerificado { get; set; }
        public Nullable<int> RutaVerificado { get; set; }
        public Nullable<int> FiltroJairo { get; set; }
        public Nullable<int> IdAsignacion { get; set; }
    }
}
