//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracterizacionAgronomicaConsultaVur
    {
        public int id { get; set; }
        public string Tipo { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public string Numero { get; set; }
        public string Area { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> idCaracterizacion { get; set; }
    }
}
