//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracterizacionCatastral
    {
        public string EXPEDIENTE { get; set; }
        public string DEPARTAMEN { get; set; }
        public string MUNICIPIO { get; set; }
        public string VeredaExpe { get; set; }
        public string NombrePred { get; set; }
        public string Tipo_Ubica { get; set; }
        public string Restriccio { get; set; }
        public string TipoRestri { get; set; }
        public string Observacio { get; set; }
        public string PresuntaPr { get; set; }
        public string Observac_1 { get; set; }
        public string NumeroPlan { get; set; }
        public Nullable<System.DateTime> FechaPlano { get; set; }
        public string DATUMplano { get; set; }
        public string Correponde { get; set; }
        public string NombreTopo { get; set; }
        public string CumpleAcue { get; set; }
        public string HojaPDFPla { get; set; }
        public Nullable<double> AreaTotalT { get; set; }
        public Nullable<double> AreaRestri { get; set; }
        public Nullable<double> AreaUtilTe { get; set; }
        public string Restricc_1 { get; set; }
        public string CualResPla { get; set; }
        public string ExisteRTDL { get; set; }
        public string Requerimie { get; set; }
        public string Requerim_1 { get; set; }
        public string Requerim_2 { get; set; }
        public string Requerim_3 { get; set; }
        public string Requerim_4 { get; set; }
        public string Requerim_5 { get; set; }
        public string Requerim_6 { get; set; }
        public Nullable<System.DateTime> FechaEdici { get; set; }
        public string UsuarioEdi { get; set; }
        public string ExistePlan { get; set; }
        public string FISO { get; set; }
        public string Inspeccion { get; set; }
        public string nPlanoIO { get; set; }
        public string Colindante { get; set; }
        public string ResConcept { get; set; }
        public string ConceptoAm { get; set; }
        public string Recomienda { get; set; }
        public string TieneRTP { get; set; }
        public string FechaRTP { get; set; }
        public string PlanoAprob { get; set; }
        public string RTDL { get; set; }
        public string AreaDescon { get; set; }
        public string ExisteInco { get; set; }
        public string FuenteRTDL { get; set; }
        public string FechaCAR { get; set; }
        public string CARConsult { get; set; }
        public string TieneRespu { get; set; }
        public string RespuestaC { get; set; }
        public string FechaURT { get; set; }
        public string DireccionC { get; set; }
        public string TieneRes_1 { get; set; }
        public string RespuestaU { get; set; }
        public string FechaINVIA { get; set; }
        public string TieneRes_2 { get; set; }
        public string RespuestaI { get; set; }
        public string FechaANH { get; set; }
        public string TieneRes_3 { get; set; }
        public string RespuestaA { get; set; }
        public string FechaANM { get; set; }
        public string TieneRes_4 { get; set; }
        public string Respuest_1 { get; set; }
        public string Requerim_7 { get; set; }
        public string FechaANI { get; set; }
        public string TieneRes_5 { get; set; }
        public string Respuest_2 { get; set; }
        public string FechaAE { get; set; }
        public string TieneRes_6 { get; set; }
        public string Respuest_3 { get; set; }
        public string FechaZRC { get; set; }
        public string TieneRes_7 { get; set; }
        public string RespuestaZ { get; set; }
        public string Esta_Georr { get; set; }
        public string CualIncons { get; set; }
        public string CumpleGeom { get; set; }
        public string ObserNoCum { get; set; }
        public string CoorDigVsC { get; set; }
        public string ExacPosici { get; set; }
        public string RazonPlano { get; set; }
        public string TraslapeEx { get; set; }
        public string TranslapeC { get; set; }
        public string Fuente_Dat { get; set; }
        public string Desplazado { get; set; }
        public string Causa_Desp { get; set; }
        public string Causa_CDgV { get; set; }
        public System.DateTime FechaInsercion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Gestion { get; set; }
        public string IdAspNetUser { get; set; }
        public string IdAspNetUserModifica { get; set; }
        public long Id { get; set; }
        public Nullable<long> IdExpediente { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
