//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public int Id { get; set; }
        public string IdAspNetUsers { get; set; }
        public Nullable<int> IdCausa { get; set; }
        public string IdOrfeo { get; set; }
        public Nullable<int> TerminoDias { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string NombrePredio { get; set; }
    }
}
