//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoGestion
    {
        public int Id { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdSoporte { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FCreacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Archivo { get; set; }
        public string IdAspNetUser { get; set; }
    }
}
