//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CtTipoIdentificacion
    {
        public int ID_CT_TIPO_IDENTIFICACION { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string NOMBRE2 { get; set; }
    }
}
