//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpedienteDocumentos
    {
        public int Id { get; set; }
        public Nullable<int> IdRetencionDocumental { get; set; }
        public Nullable<int> IdExpediente { get; set; }
        public Nullable<int> PagInicial { get; set; }
        public Nullable<int> PagFinal { get; set; }
        public string Archivo { get; set; }
        public string ArchivoUrl { get; set; }
        public bool Estado { get; set; }
        public string FechaInserta { get; set; }
        public string FechaModifica { get; set; }
        public string UsuarioInserta { get; set; }
        public string UsuarioModifica { get; set; }
    }
}
