//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneracionDocumentos
    {
        public int Id { get; set; }
        public Nullable<int> IdExpediente { get; set; }
        public Nullable<int> Validacion1 { get; set; }
        public Nullable<int> Validacion2 { get; set; }
        public Nullable<int> Validacion3 { get; set; }
        public Nullable<int> Validacion4 { get; set; }
        public Nullable<int> Validacion5 { get; set; }
        public Nullable<int> Validacion6 { get; set; }
        public Nullable<int> Validacion7 { get; set; }
        public Nullable<int> Validacion8 { get; set; }
        public Nullable<int> Validacion9 { get; set; }
        public Nullable<int> Validacion10 { get; set; }
        public Nullable<int> Gestion { get; set; }
        public string IdAspNetUser { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaCargue { get; set; }
    }
}
