//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlGestionTable
    {
        public string id { get; set; }
        public string UserName { get; set; }
        public string dia01 { get; set; }
        public string dia02 { get; set; }
        public string dia03 { get; set; }
        public string dia04 { get; set; }
        public string dia05 { get; set; }
        public string dia06 { get; set; }
        public string dia07 { get; set; }
        public string dia08 { get; set; }
        public string dia09 { get; set; }
        public string dia10 { get; set; }
        public string dia11 { get; set; }
        public string dia12 { get; set; }
        public string dia13 { get; set; }
        public string dia14 { get; set; }
        public string dia15 { get; set; }
        public string dia16 { get; set; }
        public string dia17 { get; set; }
        public string dia18 { get; set; }
        public string dia19 { get; set; }
        public string dia20 { get; set; }
        public string dia21 { get; set; }
        public string dia22 { get; set; }
        public string dia23 { get; set; }
        public string dia24 { get; set; }
        public string dia25 { get; set; }
        public string dia26 { get; set; }
        public string dia27 { get; set; }
        public string dia28 { get; set; }
        public string dia29 { get; set; }
        public string dia30 { get; set; }
        public string dia31 { get; set; }
        public int idd { get; set; }
    }
}
