//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenTipificacionAll
    {
        public int Id { get; set; }
        public int IdExpediente { get; set; }
        public string IdAspNetUser { get; set; }
        public string Grupo { get; set; }
        public Nullable<int> Plano { get; set; }
        public Nullable<int> Orden { get; set; }
        public string DeptoNombre { get; set; }
        public Nullable<int> DeptoId { get; set; }
        public string MunicNombre { get; set; }
        public Nullable<int> MunicId { get; set; }
    }
}
