//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_AspNetUsersTests_Details
    {
        public int Id { get; set; }
        public int Id_UserTest { get; set; }
        public int Id_Question { get; set; }
        public string Answer { get; set; }
    }
}
