//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_AspNetUsersTests
    {
        public int Id_UserTest { get; set; }
        public string Id_User { get; set; }
        public int Id_Test { get; set; }
        public int Id_StatusTest { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
