//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id_User { get; set; }
        public int Id_Account { get; set; }
        public string Id_Hash { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public int CreationUser { get; set; }
        public int LastChangeUser { get; set; }
        public bool RootUser { get; set; }
        public bool Active { get; set; }
        public string ImageName { get; set; }
    }
}
