//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ZonasFEntities : DbContext
    {
        public ZonasFEntities()
            : base("name=ZonasFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CtCiudad> CtCiudad { get; set; }
        public virtual DbSet<CtDepto> CtDepto { get; set; }
        public virtual DbSet<CtGenero> CtGenero { get; set; }
        public virtual DbSet<CtPais> CtPais { get; set; }
        public virtual DbSet<CtTipoIdentificacion> CtTipoIdentificacion { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Accounts_AdditionalInformation> Accounts_AdditionalInformation { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Temp_AspNetUsersTests> Temp_AspNetUsersTests { get; set; }
        public virtual DbSet<Temp_AspNetUsersTests_Details> Temp_AspNetUsersTests_Details { get; set; }
        public virtual DbSet<ExpedienteDocumentos> ExpedienteDocumentos { get; set; }
        public virtual DbSet<RetencionDocumentalGrupo> RetencionDocumentalGrupo { get; set; }
        public virtual DbSet<RetencionDocumental> RetencionDocumental { get; set; }
        public virtual DbSet<BaldiosPersonaNatural> BaldiosPersonaNatural { get; set; }
        public virtual DbSet<Registro> Registro { get; set; }
    
        public virtual int AspNetUsers_Insertar(string firstName, string lastName, string email, string passwordHash, string id)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AspNetUsers_Insertar", firstNameParameter, lastNameParameter, emailParameter, passwordHashParameter, idParameter);
        }
    }
}
