//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoAsociadoModel
    {
        public int IdAsociacion { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public string IdAspNetUser { get; set; }
        public string Rol { get; set; }

        public Nullable<System.DateTime> FechaInsercion { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
