//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.Models

{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ConceptoGestionViewModels
    {
        
        public int Id { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string NombreIdEstado { get; set; }
        public Nullable<int> IdSoporte { get; set; }
        public string NombreIdSoporte { get; set; }
        public string GestionObservacion { get; set; }
        public HttpPostedFileBase Archivo { get; set; }
        public Nullable<System.DateTime> FCreacion { get; set; }
        public Nullable<bool> Estado { get; set; }

        public string IdAspNetUserGestion { get; set; }


    }
}
